package io.github.hlfsousa.ncml.io.read;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.Proxy;
import java.util.Collections;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.github.hlfsousa.ncml.io.RuntimeConfiguration;
import io.github.hlfsousa.ncml.io.wrapper.NetcdfWrapper;
import ucar.nc2.Group;
import ucar.nc2.NetcdfFile;
import ucar.nc2.NetcdfFiles;
import ucar.unidata.io.RandomAccessFile;

public class NetcdfReader<T> {

    private static final Logger LOGGER = LoggerFactory.getLogger(NetcdfReader.class);

    private final Class<T> rootType;

    private final RuntimeConfiguration runtimeConfiguration;

    public NetcdfReader(Class<T> rootType) {
        this(rootType, new RuntimeConfiguration(Collections.emptyMap()));
    }
    
    public NetcdfReader(Class<T> rootType, RuntimeConfiguration runtimeConfiguration) {
        this.rootType = rootType;
        this.runtimeConfiguration = runtimeConfiguration;
    }
    
    @SuppressWarnings("unchecked")
    public T create() {
        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        try {
            // is there a VO class, as generated by default?
            // TODO make this a property? remove from reader? redesign reader?
            String valueObjectType = rootType.getCanonicalName() + "VO";
            return (T)classLoader.loadClass(valueObjectType).newInstance();
        } catch (Exception e) {
            return (T) Proxy.newProxyInstance(classLoader, new Class<?>[] { rootType },
                    new GroupHandler(null, false, runtimeConfiguration));
        }
    }

    @SuppressWarnings("unchecked")
    public T read(File file, boolean readOnly) throws IOException {
        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        NetcdfFile netcdf;
        if (readOnly) {
            netcdf = NetcdfFiles.open(file.getAbsolutePath());
            // if there is a NetcdfWrapper classs, as generated by default, use it
            String netcdfWrapperType = rootType.getCanonicalName() + "Wrapper";
            try {
                T wrapper = (T) classLoader.loadClass(netcdfWrapperType)
                        .getConstructor(Group.class, RuntimeConfiguration.class)
                        .newInstance(netcdf.getRootGroup(), runtimeConfiguration);
                return wrapper;
            } catch (Exception e) {
                LOGGER.debug("Wrapper class {} not found, defaulting to proxy", netcdfWrapperType, e);
            }
        } else {
            RandomAccessFile raf = new RandomAccessFile(file.getAbsolutePath(), "rw");
            netcdf = NetcdfFiles.open(raf, file.getAbsolutePath(), null, null);
        }
        return (T) Proxy.newProxyInstance(classLoader, new Class<?>[] { rootType },
                new GroupHandler(netcdf.getRootGroup(), readOnly, runtimeConfiguration));
    }

}
